export const DEVICE_MCU_MSG_R_BRIGHTNESS = 0x03;
export const DEVICE_MCU_MSG_W_BRIGHTNESS = 0x04;
export const DEVICE_MCU_MSG_R_DISP_MODE = 0x07;
export const DEVICE_MCU_MSG_W_DISP_MODE = 0x08;

export const DEVICE_MCU_MSG_R_GLASSID = 0x15;
export const DEVICE_MCU_MSG_R_DP7911_FW_VERSION = 0x16;
export const DEVICE_MCU_MSG_R_DSP_VERSION = 0x18;
export const DEVICE_MCU_MSG_W_CANCEL_ACTIVATION = 0x19;
export const DEVICE_MCU_MSG_P_HEARTBEAT = 0x1a;
export const DEVICE_MCU_MSG_W_SLEEP_TIME = 0x1e;

export const DEVICE_MCU_MSG_R_DSP_APP_FW_VERSION = 0x21;
export const DEVICE_MCU_MSG_R_MCU_APP_FW_VERSION = 0x26;
export const DEVICE_MCU_MSG_R_ACTIVATION_TIME = 0x29;
export const DEVICE_MCU_MSG_W_ACTIVATION_TIME = 0x2a;

export const DEVICE_MCU_MSG_R_DP7911_FW_IS_UPDATE = 0x3c;
export const DEVICE_MCU_MSG_W_UPDATE_DP = 0x3d;
export const DEVICE_MCU_MSG_W_UPDATE_MCU_APP_FW_PREPARE = 0x3e;
export const DEVICE_MCU_MSG_W_UPDATE_MCU_APP_FW_START = 0x3f;
export const DEVICE_MCU_MSG_W_UPDATE_MCU_APP_FW_TRANSMIT = 0x40;
export const DEVICE_MCU_MSG_W_UPDATE_MCU_APP_FW_FINISH = 0x41;
export const DEVICE_MCU_MSG_W_BOOT_JUMP_TO_APP = 0x42;
export const DEVICE_MCU_MSG_W_MCU_APP_JUMP_TO_BOOT = 0x44;
export const DEVICE_MCU_MSG_W_UPDATE_DSP_APP_FW_PREPARE = 0x45;
export const DEVICE_MCU_MSG_W_UPDATE_DSP_APP_FW_START = 0x46;
export const DEVICE_MCU_MSG_W_UPDATE_DSP_APP_FW_TRANSMIT = 0x47;
export const DEVICE_MCU_MSG_W_UPDATE_DSP_APP_FW_FINISH = 0x48;
export const DEVICE_MCU_MSG_R_IS_NEED_UPGRADE_DSP_FW = 0x49;

export const DEVICE_MCU_MSG_W_FORCE_UPGRADE_DSP_FW = 0x69;

export const DEVICE_MCU_MSG_W_BOOT_UPDATE_MODE = 0x1100;
export const DEVICE_MCU_MSG_W_BOOT_UPDATE_CONFIRM = 0x1101;
export const DEVICE_MCU_MSG_W_BOOT_UPDATE_PREPARE = 0x1102;
export const DEVICE_MCU_MSG_W_BOOT_UPDATE_START = 0x1103;
export const DEVICE_MCU_MSG_W_BOOT_UPDATE_TRANSMIT = 0x1104;
export const DEVICE_MCU_MSG_W_BOOT_UPDATE_FINISH = 0x1105;

export const DEVICE_MCU_MSG_P_START_HEARTBEAT = 0x6c02;
export const DEVICE_MCU_MSG_P_DISPLAY_TOGGLED = 0x6c04;
export const DEVICE_MCU_MSG_P_BUTTON_PRESSED = 0x6c05;
export const DEVICE_MCU_MSG_P_END_HEARTBEAT = 0x6c12;
export const DEVICE_MCU_MSG_P_ASYNC_TEXT_LOG = 0x6c09;

export const DEVICE_MCU_MSG_E_DSP_ONE_PACKGE_WRITE_FINISH = 0x6c0e;
export const DEVICE_MCU_MSG_E_DSP_UPDATE_PROGRES = 0x6c10;
export const DEVICE_MCU_MSG_E_DSP_UPDATE_ENDING = 0x6c11;

export const DEVICE_MCU_BUTTON_PHYS_DISPLAY_TOGGLE = 0x1;
export const DEVICE_MCU_BUTTON_PHYS_BRIGHTNESS_UP = 0x2;
export const DEVICE_MCU_BUTTON_PHYS_BRIGHTNESS_DOWN = 0x3;

export const DEVICE_MCU_DISPLAY_MODE_1920x1080_60 = 0x1;
export const DEVICE_MCU_DISPLAY_MODE_3840x1080_60_SBS = 0x3;
export const DEVICE_MCU_DISPLAY_MODE_3840x1080_72_SBS = 0x4;
export const DEVICE_MCU_DISPLAY_MODE_1920x1080_72 = 0x5;
export const DEVICE_MCU_DISPLAY_MODE_1920x1080_60_SBS = 0x8;
export const DEVICE_MCU_DISPLAY_MODE_3840x1080_90_SBS = 0x9;
export const DEVICE_MCU_DISPLAY_MODE_1920x1080_90 = 0xa;
export const DEVICE_MCU_DISPLAY_MODE_1920x1080_120 = 0xb;

export const DEVICE_MCU_BUTTON_VIRT_DISPLAY_TOGGLE = 0x1;
export const DEVICE_MCU_BUTTON_VIRT_BRIGHTNESS_UP = 0x6;
export const DEVICE_MCU_BUTTON_VIRT_BRIGHTNESS_DOWN = 0x7;
export const DEVICE_MCU_BUTTON_VIRT_UP = 0x8;
export const DEVICE_MCU_BUTTON_VIRT_DOWN = 0x9;
export const DEVICE_MCU_BUTTON_VIRT_MODE_2D = 0xa;
export const DEVICE_MCU_BUTTON_VIRT_MODE_3D = 0xb;
export const DEVICE_MCU_BUTTON_VIRT_BLEND_CYCLE = 0xc;
export const DEVICE_MCU_BUTTON_VIRT_CONTROL_TOGGLE = 0xf;

export const DEVICE_MCU_BLEND_STATE_LOW = 0x0;
export const DEVICE_MCU_BLEND_STATE_MEDIUM = 0x2;
export const DEVICE_MCU_BLEND_STATE_FULL = 0x3;

export const DEVICE_MCU_CONTROL_MODE_BRIGHTNESS = 0x0;
export const DEVICE_MCU_CONTROL_MODE_VOLUME = 0x1;

export const MAX_PACKET_SIZE = 64;
export const PACKET_HEAD = 0xfd;


