export const DEVICE_IMU_MSG_GET_CAL_DATA_LENGTH = 0x14;
export const DEVICE_IMU_MSG_CAL_DATA_GET_NEXT_SEGMENT = 0x15;
export const DEVICE_IMU_MSG_ALLOCATE_CAL_DATA_BUFFER = 0x16;
export const DEVICE_IMU_MSG_WRITE_CAL_DATA_SEGMENT = 0x17;
export const DEVICE_IMU_MSG_FREE_CAL_BUFFER = 0x18;
export const DEVICE_IMU_MSG_START_IMU_DATA = 0x19;
export const DEVICE_IMU_MSG_GET_STATIC_ID = 0x1A;
export const DEVICE_IMU_MSG_UNKNOWN = 0x1D;

export const GRAVITY_G = 9.806;


